# doubao_search_plugin - 自动生成的配置文件
# 基于火山引擎豆包模型的AI搜索插件

# 插件基本信息配置
[plugin]

# 插件名称 (必需)
name = "doubao_search_plugin"

# 插件版本号
version = "1.0.0"

# 是否启用插件
enabled = true

# 插件描述 (必需)
description = "基于火山引擎豆包模型的AI搜索插件"


# API相关配置，包含火山引擎API的访问信息
[api]

# API基础URL
# 示例: https://api.example.com/v1
base_url = "https://ark.cn-beijing.volces.com/api/v3"

# 模型名称
model_name = "model_name"

# 火山引擎豆包API密钥 (必需)
volcano_generate_api_key = "volcano_generate_api_key"


# 结果缓存配置
[cache]

# 是否启用请求缓存
enabled = true

# 最大缓存数量
max_size = 10


# 组件启用配置
[components]

# 是否启用搜索Action
enable_search_action = true
# 是否启用Bing搜索Action
enable_bing_action = true
# 是否启用DuckDuckGo搜索Action
enable_duckduckgo_action = true
# 是否启用Moehu图片Action
enable_pixiv_moehu_action = true
# 是否启用Pixiv随机图片Action
enable_pixiv_random_action = true
# 是否启用Pixiv排行榜图片Action
enable_pixiv_rank50_action = true




